<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <LegacyDir>..\..\..\HeuristicLab.Problems.Instances.Scheduling\3.3\</LegacyDir>
    <AssemblyName>HeuristicLab.Problems.Instances.Scheduling-3.3</AssemblyName>
    <RootNamespace>HeuristicLab.Problems.Instances.Scheduling</RootNamespace>
    <AssemblyTitle>HeuristicLab.Problems.Instances.Scheduling</AssemblyTitle>
    <AssemblyVersion>3.3.0.0</AssemblyVersion>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="$(LegacyDir)Data\JSSPORLIB.zip" LogicalName="HeuristicLab.Problems.Instances.Scheduling.Data.JSSPORLIB.zip" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HeuristicLab.Common\HeuristicLab.Common.csproj" />
    <ProjectReference Include="..\HeuristicLab.PluginInfrastructure\HeuristicLab.PluginInfrastructure.csproj" />
    <ProjectReference Include="..\HeuristicLab.Problems.Instances\HeuristicLab.Problems.Instances.csproj" />
  </ItemGroup>

</Project>
