<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <LegacyDir>..\..\..\HeuristicLab.Operators\3.3\</LegacyDir>
    <AssemblyName>HeuristicLab.Operators-3.3</AssemblyName>
    <RootNamespace>HeuristicLab.Operators</RootNamespace>
    <AssemblyTitle>HeuristicLab.Operators</AssemblyTitle>
    <Description>HeuristicLab operator classes</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\HeuristicLab.Collections\HeuristicLab.Collections.csproj" />
    <ProjectReference Include="..\HeuristicLab.Common.Resources\HeuristicLab.Common.Resources.csproj" />
    <ProjectReference Include="..\HeuristicLab.Common\HeuristicLab.Common.csproj" />
    <ProjectReference Include="..\HeuristicLab.Core\HeuristicLab.Core.csproj" />
    <ProjectReference Include="..\HeuristicLab.Data\HeuristicLab.Data.csproj" />
    <ProjectReference Include="..\HeuristicLab.Parameters\HeuristicLab.Parameters.csproj" />
    <ProjectReference Include="..\HeuristicLab.Persistence\HeuristicLab.Persistence.csproj" />
    <ProjectReference Include="..\HeuristicLab.PluginInfrastructure\HeuristicLab.PluginInfrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\extlibs\HEAL.Attic\HEAL.Attic.csproj" />
  </ItemGroup>

</Project>
