<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <LegacyDir>..\..\..\HeuristicLab.Problems.BinPacking\3.3\</LegacyDir>
    <AssemblyName>HeuristicLab.Problems.BinPacking-3.3</AssemblyName>
    <RootNamespace>HeuristicLab.Problems.BinPacking</RootNamespace>
    <AssemblyTitle>HeuristicLab.Problems.BinPacking</AssemblyTitle>
    <Description>HeuristicLab BinPacking classes</Description>
    <AssemblyVersion>3.3.0.0</AssemblyVersion>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="$(LegacyDir)3D\Instances\ContainerPackingInstances.zip" LogicalName="HeuristicLab.Problems.BinPacking._3D.Instances.ContainerPackingInstances.zip" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HeuristicLab.Analysis\HeuristicLab.Analysis.csproj" />
    <ProjectReference Include="..\HeuristicLab.Collections\HeuristicLab.Collections.csproj" />
    <ProjectReference Include="..\HeuristicLab.Common\HeuristicLab.Common.csproj" />
    <ProjectReference Include="..\HeuristicLab.Core\HeuristicLab.Core.csproj" />
    <ProjectReference Include="..\HeuristicLab.Data\HeuristicLab.Data.csproj" />
    <ProjectReference Include="..\HeuristicLab.Encodings.IntegerVectorEncoding\HeuristicLab.Encodings.IntegerVectorEncoding.csproj" />
    <ProjectReference Include="..\HeuristicLab.Encodings.PermutationEncoding\HeuristicLab.Encodings.PermutationEncoding.csproj" />
    <ProjectReference Include="..\HeuristicLab.Operators\HeuristicLab.Operators.csproj" />
    <ProjectReference Include="..\HeuristicLab.Optimization.Operators\HeuristicLab.Optimization.Operators.csproj" />
    <ProjectReference Include="..\HeuristicLab.Optimization\HeuristicLab.Optimization.csproj" />
    <ProjectReference Include="..\HeuristicLab.Parameters\HeuristicLab.Parameters.csproj" />
    <ProjectReference Include="..\HeuristicLab.Persistence\HeuristicLab.Persistence.csproj" />
    <ProjectReference Include="..\HeuristicLab.PluginInfrastructure\HeuristicLab.PluginInfrastructure.csproj" />
    <ProjectReference Include="..\HeuristicLab.Problems.Instances\HeuristicLab.Problems.Instances.csproj" />
    <ProjectReference Include="..\HeuristicLab.Random\HeuristicLab.Random.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HEAL.Attic" />
  </ItemGroup>

</Project>
